### ISSUE TITLE
Very difficult to read group authored section

### ISSUE THREAD

**Issue by khatchad** [CSCI-49900-Fall-2020/project-csci-499-clup#5]
I do not think you need quotes ('>') in this section. It makes it difficult to read.

**Comment by khatchad** [comment]
In which commit(s) was this addressed?

**Comment by KaseyHarvey98** [comment]
I thought it was for the group proposal, not the group authored, read it wrong, Sorry.

**Comment by KaseyHarvey98** [comment]
It is now fixed
